-- =====================================================================
-- FB Aero Control MRO - estrutura inicial do banco
-- Compatível com PostgreSQL (produção) e H2 em modo PostgreSQL (dev).
-- =====================================================================

-- ---------------------------------------------------------------------
-- Bases de manutenção (estações). Código ICAO do aeroporto, ex.: SBGR.
-- ---------------------------------------------------------------------
CREATE TABLE bases (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code        VARCHAR(4)   NOT NULL,
    name        VARCHAR(100) NOT NULL,
    city        VARCHAR(100) NOT NULL,
    state       VARCHAR(2)   NOT NULL,
    active      BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_bases_code UNIQUE (code)
);

-- ---------------------------------------------------------------------
-- Usuários e perfis de acesso.
--   ENGENHEIRO: Engenheiro / Administrador
--   MECANICO:   Mecânico / Técnico
--   PILOTO:     Piloto / Operador
-- As permissões de cada perfil ficam no código (enum Role).
-- ---------------------------------------------------------------------
CREATE TABLE users (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name            VARCHAR(120) NOT NULL,
    email           VARCHAR(160) NOT NULL,
    registration    VARCHAR(20)  NOT NULL,           -- matrícula
    password_hash   VARCHAR(100) NOT NULL,           -- BCrypt
    role            VARCHAR(20)  NOT NULL,
    license_number  VARCHAR(30),                     -- CANAC / licença ANAC
    active          BOOLEAN      NOT NULL DEFAULT TRUE,
    last_login_at   TIMESTAMP WITH TIME ZONE,
    created_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_users_email        UNIQUE (email),
    CONSTRAINT uk_users_registration UNIQUE (registration),
    CONSTRAINT ck_users_role CHECK (role IN ('ENGENHEIRO', 'MECANICO', 'PILOTO'))
);

-- Bases em que cada usuário pode atuar.
CREATE TABLE user_bases (
    user_id  BIGINT NOT NULL,
    base_id  BIGINT NOT NULL,
    CONSTRAINT pk_user_bases PRIMARY KEY (user_id, base_id),
    CONSTRAINT fk_user_bases_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    CONSTRAINT fk_user_bases_base FOREIGN KEY (base_id) REFERENCES bases (id)
);

-- ---------------------------------------------------------------------
-- Aeronaves.
-- ---------------------------------------------------------------------
CREATE TABLE aircraft (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    registration        VARCHAR(10)  NOT NULL,       -- matrícula, ex.: PR-FBA
    model               VARCHAR(60)  NOT NULL,
    manufacturer        VARCHAR(60)  NOT NULL,
    serial_number       VARCHAR(40)  NOT NULL,
    base_id             BIGINT       NOT NULL,
    total_flight_hours  NUMERIC(10, 1) NOT NULL DEFAULT 0,
    total_cycles        INTEGER      NOT NULL DEFAULT 0,
    status              VARCHAR(20)  NOT NULL DEFAULT 'OPERACIONAL',
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_aircraft_registration UNIQUE (registration),
    CONSTRAINT fk_aircraft_base FOREIGN KEY (base_id) REFERENCES bases (id),
    CONSTRAINT ck_aircraft_hours  CHECK (total_flight_hours >= 0),
    CONSTRAINT ck_aircraft_cycles CHECK (total_cycles >= 0),
    CONSTRAINT ck_aircraft_status CHECK (status IN ('OPERACIONAL', 'EM_MANUTENCAO', 'AOG', 'INATIVA'))
);

-- ---------------------------------------------------------------------
-- Componentes controlados (motores, trens de pouso, aviônicos...).
-- A saúde da peça (OK / WARNING / CRITICAL) é calculada pela aplicação a
-- partir de hours_since_overhaul x tbo_hours e da data de validade:
--   WARNING  = restando menos de 10% das horas até o TBO
--   CRITICAL = TBO atingido ou validade vencida
-- ---------------------------------------------------------------------
CREATE TABLE components (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aircraft_id           BIGINT,                    -- nulo = em estoque
    part_number           VARCHAR(40)  NOT NULL,     -- P/N
    serial_number         VARCHAR(40)  NOT NULL,     -- S/N
    description           VARCHAR(120) NOT NULL,
    category              VARCHAR(20)  NOT NULL,
    tbo_hours             NUMERIC(10, 1),            -- limite entre revisões
    hours_since_overhaul  NUMERIC(10, 1) NOT NULL DEFAULT 0,  -- TSO
    expiration_date       DATE,                      -- validade (quando aplicável)
    installed_at          TIMESTAMP WITH TIME ZONE,
    status                VARCHAR(20)  NOT NULL DEFAULT 'EM_ESTOQUE',
    created_at            TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at            TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_components_pn_sn UNIQUE (part_number, serial_number),
    CONSTRAINT fk_components_aircraft FOREIGN KEY (aircraft_id) REFERENCES aircraft (id),
    CONSTRAINT ck_components_tbo   CHECK (tbo_hours IS NULL OR tbo_hours > 0),
    CONSTRAINT ck_components_tso   CHECK (hours_since_overhaul >= 0),
    CONSTRAINT ck_components_category CHECK (category IN ('MOTOR', 'TREM_DE_POUSO', 'AVIONICO', 'HELICE', 'APU', 'OUTRO')),
    CONSTRAINT ck_components_status   CHECK (status IN ('INSTALADO', 'EM_ESTOQUE', 'EM_REVISAO', 'DESCARTADO'))
);

CREATE INDEX ix_components_aircraft ON components (aircraft_id);

-- ---------------------------------------------------------------------
-- Registros de horas de voo (feitos pelo Piloto / Operador).
-- Cada registro soma as horas na aeronave e nos componentes instalados.
-- ---------------------------------------------------------------------
CREATE TABLE flight_logs (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    aircraft_id  BIGINT        NOT NULL,
    pilot_id     BIGINT        NOT NULL,
    flight_date  DATE          NOT NULL,
    hours        NUMERIC(6, 1) NOT NULL,
    cycles       INTEGER       NOT NULL DEFAULT 1,
    notes        VARCHAR(500),
    created_at   TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_flight_logs_aircraft FOREIGN KEY (aircraft_id) REFERENCES aircraft (id),
    CONSTRAINT fk_flight_logs_pilot    FOREIGN KEY (pilot_id)    REFERENCES users (id),
    CONSTRAINT ck_flight_logs_hours  CHECK (hours > 0),
    CONSTRAINT ck_flight_logs_cycles CHECK (cycles >= 0)
);

CREATE INDEX ix_flight_logs_aircraft ON flight_logs (aircraft_id, flight_date);

-- ---------------------------------------------------------------------
-- Ordens de Serviço.
-- requires_approval marca serviços pesados que exigem aprovação do
-- Engenheiro (approved_by / approved_at).
-- ---------------------------------------------------------------------
CREATE TABLE work_orders (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    number             VARCHAR(20)   NOT NULL,       -- ex.: OS-2026-000001
    aircraft_id        BIGINT        NOT NULL,
    title              VARCHAR(150)  NOT NULL,
    description        VARCHAR(2000),
    type               VARCHAR(20)   NOT NULL,
    status             VARCHAR(20)   NOT NULL DEFAULT 'ABERTA',
    requires_approval  BOOLEAN       NOT NULL DEFAULT FALSE,
    opened_by          BIGINT        NOT NULL,
    assigned_to        BIGINT,
    approved_by        BIGINT,
    opened_at          TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    started_at         TIMESTAMP WITH TIME ZONE,
    completed_at       TIMESTAMP WITH TIME ZONE,
    approved_at        TIMESTAMP WITH TIME ZONE,
    updated_at         TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uk_work_orders_number UNIQUE (number),
    CONSTRAINT fk_work_orders_aircraft    FOREIGN KEY (aircraft_id) REFERENCES aircraft (id),
    CONSTRAINT fk_work_orders_opened_by   FOREIGN KEY (opened_by)   REFERENCES users (id),
    CONSTRAINT fk_work_orders_assigned_to FOREIGN KEY (assigned_to) REFERENCES users (id),
    CONSTRAINT fk_work_orders_approved_by FOREIGN KEY (approved_by) REFERENCES users (id),
    CONSTRAINT ck_work_orders_type   CHECK (type IN ('PREVENTIVA', 'CORRETIVA', 'INSPECAO')),
    CONSTRAINT ck_work_orders_status CHECK (status IN ('ABERTA', 'EM_ANDAMENTO', 'CONCLUIDA'))
);

CREATE INDEX ix_work_orders_aircraft_status ON work_orders (aircraft_id, status);

-- ---------------------------------------------------------------------
-- Serviços executados em uma OS: troca ou revisão de peças.
-- Registra quem executou, a peça removida e a peça instalada.
-- ---------------------------------------------------------------------
CREATE TABLE work_order_tasks (
    id                       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_order_id            BIGINT        NOT NULL,
    task_type                VARCHAR(20)   NOT NULL,
    removed_component_id     BIGINT,
    installed_component_id   BIGINT,
    performed_by             BIGINT        NOT NULL,
    performed_at             TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    aircraft_hours_at_task   NUMERIC(10, 1),
    notes                    VARCHAR(2000),
    CONSTRAINT fk_wo_tasks_work_order FOREIGN KEY (work_order_id)          REFERENCES work_orders (id),
    CONSTRAINT fk_wo_tasks_removed    FOREIGN KEY (removed_component_id)   REFERENCES components (id),
    CONSTRAINT fk_wo_tasks_installed  FOREIGN KEY (installed_component_id) REFERENCES components (id),
    CONSTRAINT fk_wo_tasks_performer  FOREIGN KEY (performed_by)           REFERENCES users (id),
    CONSTRAINT ck_wo_tasks_type CHECK (task_type IN ('TROCA', 'REVISAO', 'INSPECAO')),
    CONSTRAINT ck_wo_tasks_component CHECK (removed_component_id IS NOT NULL OR installed_component_id IS NOT NULL)
);

CREATE INDEX ix_wo_tasks_work_order ON work_order_tasks (work_order_id);

-- ---------------------------------------------------------------------
-- Log de auditoria (imutável): apenas INSERT.
-- No PostgreSQL, UPDATE e DELETE são bloqueados por trigger (ver
-- db/migration/postgresql). Na aplicação a entidade é @Immutable.
-- ---------------------------------------------------------------------
CREATE TABLE audit_log (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    occurred_at  TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    user_id      BIGINT,
    action       VARCHAR(40)  NOT NULL,
    entity_type  VARCHAR(40),
    entity_id    BIGINT,
    details      VARCHAR(2000),
    ip_address   VARCHAR(45),
    CONSTRAINT fk_audit_log_user FOREIGN KEY (user_id) REFERENCES users (id)
);

CREATE INDEX ix_audit_log_entity   ON audit_log (entity_type, entity_id);
CREATE INDEX ix_audit_log_occurred ON audit_log (occurred_at);
