package br.com.aerocontrol.shared.audit;

public enum AuditAction {
    LOGIN,
    LOGIN_FALHOU,
    LOGIN_NEGADO_BASE,
    LOGIN_USUARIO_INATIVO,
    USUARIO_CRIADO,
    USUARIO_ALTERADO,
    USUARIO_ATIVADO,
    USUARIO_DESATIVADO,
    SENHA_REDEFINIDA,
    AERONAVE_CRIADA,
    AERONAVE_ALTERADA,
    AERONAVE_FOTO_ALTERADA,
    AERONAVE_FOTO_REMOVIDA,
    USUARIO_FOTO_ALTERADA,
    USUARIO_FOTO_REMOVIDA
}
